# .goreleaser.yml
project_name: sandglass
builds:
  - main: cmd/sandglass/main.go
    binary: sandglass
    ldflags: -extldflags "-static"
    flags: -a -tags netgo
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - main: cmd/sandctl/main.go
    binary: sandctl
    ldflags: -extldflags "-static"
    flags: -a -tags netgo
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

brew:
  github:
    owner: celrenheit
    name: taps

  commit_author:
    name: Celrenheit
    email: celrenheit+github@gmail.com

  folder: Formula

  homepage: "https://github.com/celrenheit/sandglass"

  description: "Sandglass is a distributed, horizontally scalable, persistent, delayed message queue"
