version: '2'

services: 
    sandglass:
        build: .
        volumes:
        - ./:/gopath/src/github.com/celrenheit/sandglass
        environment:
        - GODEBUG=netdns=go
        image: celrenheit/sandglass
        
        networks:
        - my-net

    test:
        build: 
            context: .
            dockerfile: Dockerfile.test
        command: go test -v ./...
        networks:
        - my-net

    protos:
        build: 
            context: .
            dockerfile: Dockerfile.protos
        entrypoint: ash compile_protos.sh 
        volumes:
            - ./sgproto:/data/sgproto

    node1:
        extends: sandglass
        ports:
        - "2108:2108"
        command: -v --config node1.yaml --advertise_addr node1

    node2:
        extends: sandglass
        command: -v --config node2.yaml --advertise_addr node2

    node3:
        extends: sandglass
        command: -v --config node3.yaml --advertise_addr node3

    integration_test:
        extends: sandglass
        command: go test -v ./integration/broker

    releaser:
        build: 
            context: .
            dockerfile: Dockerfile.releaser
        environment:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        command: goreleaser

networks:
  my-net: