version: '2'

services: 
    sandglass:
        build: .
        volumes:
        - ./:/gopath/src/github.com/celrenheit/sandglass
        environment:
        - GODEBUG=netdns=go
        image: celrenheit/sandglass
        
        networks:
        - my-net

    test:
        build: 
            context: .
            dockerfile: Dockerfile.test
        command: go test -v ./...
        networks:
        - my-net

    protos:
        build: 
            context: .
            dockerfile: Dockerfile.protos
        entrypoint: ash compile_protos.sh 
        volumes:
            - ./sgproto:/data/sgproto

    node1:
        extends: sandglass
        ports:
        - "2201:2201"
        - "3301:3301"
        command: --config node1.yaml

    node2:
        extends: sandglass
        ports:
        - "2202:2202"
        - "3302:3302"
        command: --config node2.yaml

    integration_test:
        extends: sandglass
        command: go test -v ./integration/broker

    releaser:
        build: 
            context: .
            dockerfile: Dockerfile.releaser
        environment:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        command: goreleaser

networks:
  my-net: